/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm_green_uni;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class SubjectRegis extends javax.swing.JFrame {

    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public SubjectRegis() {
        initComponents();
    }
    void f_clearData(){
        s_id.setText("");
        s_name.setText("");
        
        subj1.setSelectedItem("");
        subj2.setSelectedItem("");
        subj3.setSelectedItem("");
        subj4.setSelectedItem("");
        subj5.setSelectedItem("");
        subj6.setSelectedItem("");
        subj7.setSelectedItem("");
        subj8.setSelectedItem("");

    }
    void j_clearData(){
        j_id.setText("");
        j_name.setText("");
        
        j_sub1.setSelectedItem("");
        j_sub2.setSelectedItem("");
        j_sub3.setSelectedItem("");
        j_sub4.setSelectedItem("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        j_id = new javax.swing.JTextField();
        j_name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        j_sub1 = new javax.swing.JComboBox<>();
        j_sub2 = new javax.swing.JComboBox<>();
        j_sub3 = new javax.swing.JComboBox<>();
        j_sub4 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        f4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        s_id = new javax.swing.JTextField();
        s_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        subj7 = new javax.swing.JComboBox<>();
        subj8 = new javax.swing.JComboBox<>();
        subj6 = new javax.swing.JComboBox<>();
        subj1 = new javax.swing.JComboBox<>();
        subj2 = new javax.swing.JComboBox<>();
        subj5 = new javax.swing.JComboBox<>();
        subj4 = new javax.swing.JComboBox<>();
        subj3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        fc1 = new javax.swing.JLabel();
        fc2 = new javax.swing.JLabel();
        fc3 = new javax.swing.JLabel();
        fc4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ff1 = new javax.swing.JLabel();
        ff2 = new javax.swing.JLabel();
        ff3 = new javax.swing.JLabel();
        ff4 = new javax.swing.JLabel();
        fc8 = new javax.swing.JLabel();
        fc6 = new javax.swing.JLabel();
        fc7 = new javax.swing.JLabel();
        fc5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ff5 = new javax.swing.JLabel();
        ff6 = new javax.swing.JLabel();
        ff7 = new javax.swing.JLabel();
        ff8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText(" Selecte Optional Subjects");

        jLabel8.setText("Student ID");

        jLabel9.setText("Student Name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Semester 2");

        j_sub1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Management IS", "Marketing" }));
        j_sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_sub1ActionPerformed(evt);
            }
        });

        j_sub2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Econ", "Enhancement" }));
        j_sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_sub2ActionPerformed(evt);
            }
        });

        j_sub3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maths 2", "Econ 2" }));
        j_sub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_sub3ActionPerformed(evt);
            }
        });

        j_sub4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marketing 2" }));
        j_sub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_sub4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("credits");

        c1.setText("c");

        c2.setText("c");

        c3.setText("c");

        c4.setText("c");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("fees");

        f1.setText("$");

        f2.setText("$");

        f3.setText("$");

        f4.setText("$");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j_id, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(j_name)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(j_sub4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j_sub1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j_sub2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j_sub3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(212, 212, 212)
                        .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(f1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(f2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(j_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(j_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_sub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1)
                    .addComponent(f1))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_sub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2)
                    .addComponent(f2))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(j_sub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c3)
                        .addComponent(f3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j_sub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c4))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(f4)
                        .addGap(85, 85, 85))))
        );

        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton14.setText("SUBMIT");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 169, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton14))
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("July", jPanel9);

        jLabel3.setText("Student ID");

        jLabel4.setText("Student Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Semester 1");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Semester 2");

        jButton13.setText("SUBMIT");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        subj7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maths 2", "Econ 2" }));
        subj7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subj7ActionPerformed(evt);
            }
        });

        subj8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marketing 2" }));
        subj8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subj8ActionPerformed(evt);
            }
        });

        subj6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Econ", "Enhancement" }));
        subj6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subj6ActionPerformed(evt);
            }
        });

        subj1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Business Communication", "Business English" }));
        subj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subj1ActionPerformed(evt);
            }
        });

        subj2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Financial Accounting", "Economics" }));
        subj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subj2ActionPerformed(evt);
            }
        });

        subj5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Management IS", "Marketing" }));
        subj5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subj5ActionPerformed(evt);
            }
        });

        subj4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quality Management", "strategic management" }));
        subj4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subj4ActionPerformed(evt);
            }
        });

        subj3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Management Process", "Logistics Management" }));
        subj3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subj3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("credits");

        fc1.setText("c");

        fc2.setText("c");

        fc3.setText("c");

        fc4.setText("c");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("fees");

        ff1.setText("$");

        ff2.setText("$");

        ff3.setText("$");

        ff4.setText("$");

        fc8.setText("c");

        fc6.setText("c");

        fc7.setText("c");

        fc5.setText("c");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("credits");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("fees");

        ff5.setText("$");

        ff6.setText("$");

        ff7.setText("$");

        ff8.setText("$");

        jButton2.setText("Dashboard");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(108, 108, 108)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(s_id, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(s_name))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subj2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subj4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subj3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(199, 199, 199)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(ff1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(151, 151, 151)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(subj5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(subj6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(subj7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(57, 57, 57)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(fc5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fc6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fc7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fc8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jButton13))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ff8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ff5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ff7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ff6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton2))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ff2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ff3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ff4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(151, 151, 151)
                                        .addComponent(subj8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)))
                                .addGap(1, 1, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(267, 267, 267))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fc4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(87, 87, 87)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(77, 77, 77))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subj5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(subj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fc1)
                                .addComponent(ff1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subj2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fc2)
                            .addComponent(ff2)
                            .addComponent(subj6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fc6)
                            .addComponent(ff6))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subj3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fc3)
                            .addComponent(ff3)
                            .addComponent(subj7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fc7)
                            .addComponent(ff7))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subj8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(subj4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fc4)
                                .addComponent(ff4)
                                .addComponent(fc8)
                                .addComponent(ff8))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(s_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(s_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fc5)
                            .addComponent(ff5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("February", jPanel8);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        String id=j_id.getText();
        String name=j_name.getText();

        String sub1=j_sub1.getSelectedItem().toString();
        String sub2=j_sub2.getSelectedItem().toString();
        String sub3=j_sub3.getSelectedItem().toString();
        String sub4=j_sub4.getSelectedItem().toString();
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "INSERT INTO `july_subjects` VALUES (?,?,?,?,?,?)";
            pst=con.prepareStatement(sql);

            pst.setString(1,id);
            pst.setString(2,name);

            pst.setString(3,sub1);
            pst.setString(4,sub2);
            pst.setString(5,sub3);
            pst.setString(6,sub4);
            pst.executeUpdate();
        }
        catch (Exception e){
            System.err.print(e);
        }
        JOptionPane.showMessageDialog(this, "Successfully saved");
        j_clearData();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void j_sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_sub1ActionPerformed
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "SELECT subjectName,Fees,Credit FROM subjects";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String sub = rs.getString("subjectName");
                String f = rs.getString("Fees");
                String cred = rs.getString("Credit");

                if (sub.equals(j_sub1.getSelectedItem().toString())) {
                    c1.setText(cred);
                    f1.setText(f);
                }
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_j_sub1ActionPerformed

    private void j_sub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_sub2ActionPerformed
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "SELECT subjectName,Fees,Credit FROM subjects";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String sub = rs.getString("subjectName");
                String f = rs.getString("Fees");
                String cred = rs.getString("Credit");

                if (sub.equals(j_sub2.getSelectedItem().toString())) {
                    c2.setText(cred);
                    f2.setText(f);
                }
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_j_sub2ActionPerformed

    private void j_sub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_sub3ActionPerformed
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "SELECT subjectName,Fees,Credit FROM subjects";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String sub = rs.getString("subjectName");
                String f = rs.getString("Fees");
                String cred = rs.getString("Credit");

                if (sub.equals(j_sub3.getSelectedItem().toString())) {
                    c3.setText(cred);
                    f3.setText(f);
                }
            }

        }  catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_j_sub3ActionPerformed

    private void j_sub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_sub4ActionPerformed
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "SELECT subjectName,Fees,Credit FROM subjects";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String sub = rs.getString("subjectName");
                String f = rs.getString("Fees");
                String cred = rs.getString("Credit");

                if (sub.equals(j_sub4.getSelectedItem().toString())) {
                    c4.setText(cred);
                    f4.setText(f);
                }
            }

        }  catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_j_sub4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String id=s_id.getText();
        String name=s_name.getText();

        String sub1=subj1.getSelectedItem().toString();
        String sub2=subj2.getSelectedItem().toString();
        String sub3=subj3.getSelectedItem().toString();
        String sub4=subj4.getSelectedItem().toString();
        String sub5=subj5.getSelectedItem().toString();
        String sub6=subj6.getSelectedItem().toString();
        String sub7=subj7.getSelectedItem().toString();
        String sub8=subj8.getSelectedItem().toString();
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "INSERT INTO `february_subjects` VALUES (?,?,?,?,?,?,?,?,?,?)";
            pst=con.prepareStatement(sql);

            pst.setString(1,id);
            pst.setString(2,name);

            pst.setString(3,sub1);
            pst.setString(4,sub2);
            pst.setString(5,sub3);
            pst.setString(6,sub4);
            pst.setString(7,sub5);
            pst.setString(8,sub6);
            pst.setString(9,sub7);
            pst.setString(10,sub8);
            pst.executeUpdate();
        }
        catch (Exception e){
            System.err.print(e);
        }

        JOptionPane.showMessageDialog(this, "Successfully saved");
        f_clearData();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void subj7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subj7ActionPerformed
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "SELECT subjectName,Fees,Credit FROM subjects";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String sub = rs.getString("subjectName");
                String f = rs.getString("Fees");
                String cred = rs.getString("Credit");

                if (sub.equals(subj7.getSelectedItem().toString())) {
                    fc7.setText(cred);
                    ff7.setText(f);
                }
            }

        } catch (Exception e) {
            System.err.print(e);
        }
    }//GEN-LAST:event_subj7ActionPerformed

    private void subj8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subj8ActionPerformed
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "SELECT subjectName,Fees,Credit FROM subjects";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String sub = rs.getString("subjectName");
                String f = rs.getString("Fees");
                String cred = rs.getString("Credit");

                if (sub.equals(subj8.getSelectedItem().toString())) {
                    fc8.setText(cred);
                    ff8.setText(f);
                }
            }

        } catch (Exception e) {
            System.err.print(e);
        }
    }//GEN-LAST:event_subj8ActionPerformed

    private void subj6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subj6ActionPerformed
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "SELECT subjectName,Fees,Credit FROM subjects";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String sub = rs.getString("subjectName");
                String f = rs.getString("Fees");
                String cred = rs.getString("Credit");

                if (sub.equals(subj6.getSelectedItem().toString())) {
                    fc6.setText(cred);
                    ff6.setText(f);
                }
            }

        } catch (Exception e) {
                        System.err.print(e);

        }
    }//GEN-LAST:event_subj6ActionPerformed

    private void subj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subj1ActionPerformed
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "SELECT subjectName,Fees,Credit FROM subjects";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String sub = rs.getString("subjectName");
                String f = rs.getString("Fees");
                String cred = rs.getString("Credit");

                if (sub.equals(subj1.getSelectedItem().toString())) {
                    fc1.setText(cred);
                    ff1.setText(f);
                }
            }

        } catch (Exception e) {
            System.err.print(e);
        }
    }//GEN-LAST:event_subj1ActionPerformed

    private void subj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subj2ActionPerformed
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "SELECT subjectName,Fees,Credit FROM subjects";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String sub = rs.getString("subjectName");
                String f = rs.getString("Fees");
                String cred = rs.getString("Credit");

                if (sub.equals(subj2.getSelectedItem().toString())) {
                    fc2.setText(cred);
                    ff2.setText(f);
                }
            }

        } catch (Exception e) {
            System.err.print(e);
        }
    }//GEN-LAST:event_subj2ActionPerformed

    private void subj5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subj5ActionPerformed
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "SELECT subjectName,Fees,Credit FROM subjects";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String sub = rs.getString("subjectName");
                String f = rs.getString("Fees");
                String cred = rs.getString("Credit");

                if (sub.equals(subj5.getSelectedItem().toString())) {
                    fc5.setText(cred);
                    ff5.setText(f);
                }
            }

        } catch (Exception e) {
            System.err.print(e);
        }
    }//GEN-LAST:event_subj5ActionPerformed

    private void subj4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subj4ActionPerformed
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "SELECT subjectName,Fees,Credit FROM subjects";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String sub = rs.getString("subjectName");
                String f = rs.getString("Fees");
                String cred = rs.getString("Credit");

                if (sub.equals(subj4.getSelectedItem().toString())) {
                    fc4.setText(cred);
                    ff4.setText(f);
                }
            }

        } catch (Exception e) {
            System.err.print(e);
        }
    }//GEN-LAST:event_subj4ActionPerformed

    private void subj3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subj3ActionPerformed
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nsbm", "root", "");
            String sql = "SELECT subjectName,Fees,Credit FROM subjects";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String sub = rs.getString("subjectName");
                String f = rs.getString("Fees");
                String cred = rs.getString("Credit");

                if (sub.equals(subj3.getSelectedItem().toString())) {
                    fc3.setText(cred);
                    ff3.setText(f);
                }
            }

        } catch (Exception e) {
            System.err.print(e);
        }
    }//GEN-LAST:event_subj3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Dashboard d=new Dashboard();
        d.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectRegis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel fc1;
    private javax.swing.JLabel fc2;
    private javax.swing.JLabel fc3;
    private javax.swing.JLabel fc4;
    private javax.swing.JLabel fc5;
    private javax.swing.JLabel fc6;
    private javax.swing.JLabel fc7;
    private javax.swing.JLabel fc8;
    private javax.swing.JLabel ff1;
    private javax.swing.JLabel ff2;
    private javax.swing.JLabel ff3;
    private javax.swing.JLabel ff4;
    private javax.swing.JLabel ff5;
    private javax.swing.JLabel ff6;
    private javax.swing.JLabel ff7;
    private javax.swing.JLabel ff8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField j_id;
    private javax.swing.JTextField j_name;
    private javax.swing.JComboBox<String> j_sub1;
    private javax.swing.JComboBox<String> j_sub2;
    private javax.swing.JComboBox<String> j_sub3;
    private javax.swing.JComboBox<String> j_sub4;
    private javax.swing.JTextField s_id;
    private javax.swing.JTextField s_name;
    private javax.swing.JComboBox<String> subj1;
    private javax.swing.JComboBox<String> subj2;
    private javax.swing.JComboBox<String> subj3;
    private javax.swing.JComboBox<String> subj4;
    private javax.swing.JComboBox<String> subj5;
    private javax.swing.JComboBox<String> subj6;
    private javax.swing.JComboBox<String> subj7;
    private javax.swing.JComboBox<String> subj8;
    // End of variables declaration//GEN-END:variables
}
